# Generated by Django 5.1.6 on 2025-03-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='description',
        ),
        migrations.CreateModel(
            name='More',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proimage', models.ImageField(upload_to='items/')),
                ('description', models.TextField()),
                ('Item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='app.items')),
            ],
        ),
    ]
