# Generated by Django 5.1.6 on 2025-03-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_model1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('number_of_people', models.PositiveIntegerField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.model1')),
            ],
        ),
    ]
