# Generated by Django 5.1.4 on 2025-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name1',
            field=models.CharField(default='anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
