# Generated by Django 5.1.4 on 2025-03-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_review_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name1',
        ),
        migrations.AddField(
            model_name='review',
            name='instance',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.model1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
